# Generated by Django 4.2.5 on 2023-09-21 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_book_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
