# Generated by Django 4.2.5 on 2023-09-25 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_book_rental_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('vente', 'Vente'), ('location', 'Location')], default='vente', max_length=10),
        ),
    ]
