# Generated by Django 4.2.5 on 2023-09-25 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_book_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
    ]
